image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
  - choco install GitVersion.Portable --version 4.0.0
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion

test_script:
  - ps: src\test.ps1

artifacts:
  - path: artifacts\Release\*.nupkg

deploy:
  provider: Environment
  name: NuGet
  on:
    appveyor_repo_tag: true
