var searchData=
[
  ['ichangenotify_948',['IChangeNotify',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_change_notify.html',1,'NanoByte::Common::Dispatch']]],
  ['icloneable_949',['ICloneable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20localizablestring_20_3e_950',['ICloneable&lt; LocalizableString &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20localizablestringcollection_20_3e_951',['ICloneable&lt; LocalizableStringCollection &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionary_20_3e_952',['ICloneable&lt; XmlDictionary &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionaryentry_20_3e_953',['ICloneable&lt; XmlDictionaryEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icommandexecutor_954',['ICommandExecutor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor.html',1,'NanoByte::Common::Undo']]],
  ['icommandmanager_955',['ICommandManager',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager.html',1,'NanoByte::Common::Undo']]],
  ['icontainerdescription_956',['IContainerDescription',['../interface_nano_byte_1_1_structure_editor_1_1_i_container_description.html',1,'NanoByte::StructureEditor']]],
  ['icontextmenu_957',['IContextMenu',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu.html',1,'NanoByte::Common::Controls']]],
  ['icredentialprovider_958',['ICredentialProvider',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider.html',1,'NanoByte::Common::Net']]],
  ['ieditordialog_959',['IEditorDialog',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog.html',1,'NanoByte::Common::Controls']]],
  ['ihighlightcolor_960',['IHighlightColor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_highlight_color.html',1,'NanoByte::Common']]],
  ['ilistdescription_961',['IListDescription',['../interface_nano_byte_1_1_structure_editor_1_1_i_list_description.html',1,'NanoByte::StructureEditor']]],
  ['images_962',['Images',['../class_nano_byte_1_1_structure_editor_1_1_win_forms_1_1_resources_1_1_images.html',1,'NanoByte::StructureEditor::WinForms::Resources']]],
  ['imergeable_963',['IMergeable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['inamed_964',['INamed',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inodeeditor_965',['INodeEditor',['../interface_nano_byte_1_1_structure_editor_1_1_i_node_editor.html',1,'NanoByte::StructureEditor']]],
  ['inputbox_966',['InputBox',['https://common.nano-byte.net/class_nano_byte_1_1_common_1_1_controls_1_1_input_box.html',1,'NanoByte::Common::Controls']]],
  ['istructureeditor_967',['IStructureEditor',['../interface_nano_byte_1_1_structure_editor_1_1_i_structure_editor.html',1,'NanoByte::StructureEditor']]],
  ['itargetcontainerinject_968',['ITargetContainerInject',['../interface_nano_byte_1_1_structure_editor_1_1_i_target_container_inject.html',1,'NanoByte::StructureEditor']]],
  ['itask_969',['ITask',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task.html',1,'NanoByte::Common::Tasks']]],
  ['itaskhandler_970',['ITaskHandler',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler.html',1,'NanoByte::Common::Tasks']]],
  ['itouchcontrol_971',['ITouchControl',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control.html',1,'NanoByte::Common::Controls']]],
  ['iundocommand_972',['IUndoCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command.html',1,'NanoByte::Common::Undo']]],
  ['ivaluecommand_973',['IValueCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command.html',1,'NanoByte::Common::Undo']]],
  ['iwizardpage_974',['IWizardPage',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_wizard_page.html',1,'NanoByte::Common::Controls']]]
];
